const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        screens: {
            xs: '375px',
            sm: '768px',
            md: '1024px',
            lg: '1280px',
            xl: '1440px',
        },
        fontFamily: {
            sans: ['nunito-sans', ...defaultTheme.fontFamily.sans],
            mono: ['Roboto Mono', 'SFMono-Regular'],
        },
        colors: {
            transparent: 'transparent',
            white: '#fff',
            black: {
                '100': '#1b1b1b',
                '100a95': 'rgba(27,27,27,0.95)',
                '200': '#000',
            },
            gray: {
                '100': '#f7f7f7',
                '200': '#e8e8e8',
                '300': '#d1d1d1',
                '400': '#c4c4c4',
            },
        },
        fontSize: {
            'xs': '13px', // 13px
            'sm': '15px', // 15px
            'base': '16px', // 16px
            'lg': '18px', // 18px
            'xl': '20px', // 20px
            '2xl': '24px', // 24px
            '3xl': '26px', // 26px
            '4xl': '27px', // 27px
            '5xl': '32px', // 32px
            '6xl': '34px', // 34px
            '7xl': '36px', // 36px
            '8xl': '44px', // 44px
            '9xl': '58px', // 58px
        },
        lineHeight: {
            xs: '0.9',
            none: '1',
            base: '1.556',
            normal: '1.375',
            a1: '1.1',
            a17: '1.17',
            a16: '1.16',
            a2: '1.2',
            a22: '1.22',
            a23: '1.23',
            a25: '1.25',
            a31: '1.31',
            a35: '1.35',
            a36: '1.36',
            a4: '1.4',
            a43: '1.43',
        },
        letterSpacing: {
            tighter: '-0.02em',
            tight: '-0.01em',
            normal: '0',
            'a3': '0.3px',
            'a5': '0.5px',
        },
        fontWeight: {
            hairline: '100',
            thin: '200',
            light: '300',
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
            extrabold: '800',
            black: '900',
        },
        extend: {
            spacing: {
                'auto': 'auto',
                'px': '1px',
                '0': '0',
                '1': '1px',
                '2': '2px',
                '3': '3px',
                '4': '4px',
                '5': '5px',
                '6': '6px',
                '7': '7px',
                '8': '8px',
                '9': '9px',
                '10': '10px',
                '11': '11px',
                '12': '12px',
                '13': '13px',
                '14': '14px',
                '15': '15px',
                '16': '16px',
                '17': '17px',
                '18': '18px',
                '19': '19px',
                '20': '20px',
                '20': '20px',
                '21': '21px',
                '22': '22px',
                '23': '23px',
                '24': '24px',
                '25': '25px',
                '26': '26px',
                '27': '27px',
                '28': '28px',
                '29': '29px',
                '30': '30px',
                '31': '31px',
                '32': '32px',
                '33': '33px',
                '34': '34px',
                '35': '35px',
                '36': '36px',
                '37': '37px',
                '38': '38px',
                '39': '39px',
                '31': '31px',
                '32': '32px',
                '33': '33px',
                '34': '34px',
                '35': '35px',
                '36': '36px',
                '37': '37px',
                '38': '38px',
                '39': '39px',
                '40': '40px',
                '41': '41px',
                '42': '42px',
                '43': '43px',
                '44': '44px',
                '45': '45px',
                '46': '46px',
                '47': '47px',
                '48': '48px',
                '49': '49px',
                '41': '41px',
                '42': '42px',
                '43': '43px',
                '44': '44px',
                '45': '45px',
                '46': '46px',
                '47': '47px',
                '48': '48px',
                '49': '49px',
                '50': '50px',
                '51': '51px',
                '52': '52px',
                '53': '53px',
                '54': '54px',
                '55': '55px',
                '56': '56px',
                '57': '57px',
                '58': '58px',
                '59': '59px',
                '60': '60px',
                '61': '61px',
                '62': '62px',
                '63': '63px',
                '64': '64px',
                '65': '65px',
                '66': '66px',
                '67': '67px',
                '68': '68px',
                '69': '69px',
                '70': '70px',
            },
            padding: theme => ({
                ...theme('spacing'),
                '56p': '50%',
                full: '100%',
            }),
            margin: (theme, { negative }) => ({
                auto: 'auto',
                ...theme('spacing'),
                ...negative(theme('spacing')),
            }),
            maxHeight: {
                auto: 'auto',
                '187': '187px',
            },
            maxWidth: {
                none: 'none',
                auto: 'auto',
                full: '100%',
                lg: '1000px',
                xl: '1344px',
            },
            minHeight: {
                auto: 'auto',
                screen: '100vh',
                '108': '108px',
            },
            minWidth: {
                auto: 'auto',
            },
            height: theme => ({
                auto: 'auto',
                full: '100%',
                ...theme('spacing'),
                '1p': '1%',
                screen: '100vh',
                screen86: 'calc(100vh - 86px)',
                screen92: 'calc(100vh - 92px)',
            }),
            width: theme => ({
                auto: 'auto',
                ...theme('spacing'),
                ...theme('spacingGrid'),
                screen: '100vw',
                'c50-p132': 'calc(50vw + 132px)',
                'c318': 'calc(100% - 318px)',
                '35p': '35%',
                '56p': '56%',
            }),
            backgroundImage: {
                'marble-pattern': "url('/images/marble-pattern.png')",
                'glass-pattern': "url('/images/glass-pattern.png')",
            },
            translate: {
                '-full': '-100%',
                '-1/2': '-50%',
                '1/2': '50%',
                full: '100%',
            },
            rotate: {
                '-180': '-180deg',
                '-90': '-90deg',
                '-45': '-45deg',
                '0': '0',
                '45': '45deg',
                '90': '90deg',
                '180': '180deg',
            },
            borderRadius: {
                none: '0',
                '2': '2px',
                '3': '3px',
                '4': '4px',
                '5': '5px',
                full: '9999px',
            },
            inset: {
                '-5': '-5px',
                '0': '0',
                '8': '8px',
                half: '50%',
                full: '100%',
            },
            zIndex: {
                auto: 'auto',
                '-1': -1,
                '0': 0,
                '1': 1,
                '2': 2,
                '3': 3,
                '4': 4,
                '5': 5,
                '6': 6,
                '7': 7,
                '8': 8,
                '9': 9,
                '10': 10,
                '20': 20,
                '30': 30,
                '40': 40,
                '50': 50,
                '99': 99,
                '100': 100,
            },
            transitionProperty: {
                none: 'none',
                all: 'all',
                default: 'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
                colors: 'background-color, border-color, color, fill, stroke',
                opacity: 'opacity',
                shadow: 'box-shadow',
                transform: 'transform',
            },
            boxShadow: {
                xs: '0 2.48649px 14.9189px rgba(0, 0, 0, 0.04)',
                sm: '0 2px 8px rgba(0, 0, 0, 0.16)',
                border: '0 0 0 1px #3d3d3d',
                'border-hover': '0 0 0 2px #1045ff',
                none: 'none',
            },
        },
        flex: {
            '1': '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
            '1/2': '0 0 50%',
            '2/3': '0 0 67.667%',
            '1/3': '0 0 33.33%'
        }
    },

    variants: {
        accessibility: ['responsive', 'focus'],
        alignContent: ['responsive'],
        alignItems: ['responsive'],
        alignSelf: ['responsive'],
        appearance: ['responsive'],
        backgroundAttachment: ['responsive'],
        backgroundColor: ['responsive', 'hover', 'focus'],
        backgroundPosition: ['responsive'],
        backgroundRepeat: ['responsive'],
        backgroundSize: ['responsive'],
        borderCollapse: ['responsive'],
        borderColor: ['responsive', 'hover', 'focus'],
        borderRadius: ['responsive'],
        borderStyle: ['responsive'],
        borderWidth: ['responsive'],
        boxShadow: ['responsive', 'hover', 'focus'],
        boxSizing: ['responsive'],
        cursor: ['responsive'],
        display: ['responsive'],
        fill: ['responsive'],
        flex: ['responsive'],
        flexDirection: ['responsive'],
        flexGrow: ['responsive'],
        flexShrink: ['responsive'],
        flexWrap: ['responsive'],
        float: ['responsive'],
        clear: ['responsive'],
        fontFamily: ['responsive'],
        fontSize: ['responsive'],
        fontSmoothing: ['responsive'],
        fontStyle: ['responsive'],
        fontWeight: ['responsive', 'hover', 'focus'],
        height: ['responsive'],
        inset: ['responsive'],
        justifyContent: ['responsive'],
        letterSpacing: ['responsive'],
        lineHeight: ['responsive'],
        listStylePosition: ['responsive'],
        listStyleType: ['responsive'],
        margin: ['responsive'],
        maxHeight: ['responsive'],
        maxWidth: ['responsive'],
        minHeight: ['responsive'],
        minWidth: ['responsive'],
        objectFit: ['responsive'],
        objectPosition: ['responsive'],
        opacity: ['responsive', 'hover', 'focus'],
        order: ['responsive'],
        outline: ['responsive', 'focus'],
        overflow: ['responsive'],
        padding: ['responsive'],
        placeholderColor: ['responsive', 'focus'],
        pointerEvents: ['responsive'],
        position: ['responsive'],
        resize: ['responsive'],
        stroke: ['responsive'],
        strokeWidth: ['responsive'],
        tableLayout: ['responsive'],
        textAlign: ['responsive'],
        textColor: ['responsive', 'hover', 'focus'],
        textDecoration: ['responsive', 'hover', 'focus'],
        textTransform: ['responsive'],
        userSelect: ['responsive'],
        verticalAlign: ['responsive'],
        visibility: ['responsive'],
        whitespace: ['responsive'],
        width: ['responsive'],
        wordBreak: ['responsive'],
        zIndex: ['responsive'],
        gap: ['responsive'],
        gridAutoFlow: ['responsive'],
        gridTemplateColumns: ['responsive'],
        gridColumn: ['responsive'],
        gridColumnStart: ['responsive'],
        gridColumnEnd: ['responsive'],
        gridTemplateRows: ['responsive'],
        gridRow: ['responsive'],
        gridRowStart: ['responsive'],
        gridRowEnd: ['responsive'],
        transform: ['responsive'],
        transformOrigin: ['responsive'],
        scale: ['responsive', 'hover', 'focus'],
        rotate: ['responsive', 'hover', 'focus'],
        translate: ['responsive', 'hover', 'focus'],
        skew: ['responsive', 'hover', 'focus'],
        transitionProperty: ['responsive'],
        transitionTimingFunction: ['responsive'],
        transitionDuration: ['responsive'],
    },
};
